function mln_Gen_NMM_fs_vs_ns_hc(dirname,prename,nc,is,npts,fs)
% generate the data for given fs with varying cs

% dirname: the folder to store all files
% prenom: spectial name for new datasets
% nc: the channels of data
% is: which structure stored in the structure file
% npts: length of data
% cs: the connection strength

% -----------------------------------------------------
% Examples:mln_Gen_NMM_fs_vs Examples nmm 20 1 810 0.1 1 10 250
% Note that: there should be a structureN*L*S10.mat file in the dirname
% folder
% structureN*L*S10.mat can be generated by calling function
% './FindStructures/mln_gen_structure_Nodes.m'
% -------------------------------------------------------------------------

% Huifang Wang, Marseille, Dec 3, 2014
% -------------------------------------------------------------------------

datadir=[dirname,'/data'];
if ~exist(datadir,'dir')
    try mkdir(datadir);
    end
end


strfile=[dirname,'/','stru100hConN',nc];

if ~exist([strfile,'.mat'],'file')
display('Nostrfile')
end


is=str2double(is);
nc=str2double(nc);

npts=str2double(npts);
fs=str2double(fs);   


mln_generate_nmm_vcs_fs_hc(is,nc,strfile,dirname,prename,npts,fs); 